/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampfiresNewRouteImport } from './routes/campfires/new'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as CSlugWallRouteImport } from './routes/c/$slug/wall'
import { Route as CSlugSettingsRouteImport } from './routes/c/$slug/settings'
import { Route as CSlugPhotosRouteImport } from './routes/c/$slug/photos'
import { Route as CSlugJoinRouteImport } from './routes/c/$slug/join'
import { Route as CSlugHomeRouteImport } from './routes/c/$slug/home'
import { Route as CSlugEventsRouteImport } from './routes/c/$slug/events'
import { Route as CSlugAlbumRouteImport } from './routes/c/$slug/album'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampfiresNewRoute = CampfiresNewRouteImport.update({
  id: '/campfires/new',
  path: '/campfires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/c/$slug/',
  path: '/c/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugWallRoute = CSlugWallRouteImport.update({
  id: '/c/$slug/wall',
  path: '/c/$slug/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugSettingsRoute = CSlugSettingsRouteImport.update({
  id: '/c/$slug/settings',
  path: '/c/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugPhotosRoute = CSlugPhotosRouteImport.update({
  id: '/c/$slug/photos',
  path: '/c/$slug/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugJoinRoute = CSlugJoinRouteImport.update({
  id: '/c/$slug/join',
  path: '/c/$slug/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugHomeRoute = CSlugHomeRouteImport.update({
  id: '/c/$slug/home',
  path: '/c/$slug/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugEventsRoute = CSlugEventsRouteImport.update({
  id: '/c/$slug/events',
  path: '/c/$slug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugAlbumRoute = CSlugAlbumRouteImport.update({
  id: '/c/$slug/album',
  path: '/c/$slug/album',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/home': typeof CSlugHomeRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/photos': typeof CSlugPhotosRoute
  '/c/$slug/settings': typeof CSlugSettingsRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug/': typeof CSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/home': typeof CSlugHomeRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/photos': typeof CSlugPhotosRoute
  '/c/$slug/settings': typeof CSlugSettingsRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug': typeof CSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/events': typeof CSlugEventsRoute
  '/c/$slug/home': typeof CSlugHomeRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/photos': typeof CSlugPhotosRoute
  '/c/$slug/settings': typeof CSlugSettingsRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug/': typeof CSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/profile'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug/album'
    | '/c/$slug/events'
    | '/c/$slug/home'
    | '/c/$slug/join'
    | '/c/$slug/photos'
    | '/c/$slug/settings'
    | '/c/$slug/wall'
    | '/c/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/profile'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug/album'
    | '/c/$slug/events'
    | '/c/$slug/home'
    | '/c/$slug/join'
    | '/c/$slug/photos'
    | '/c/$slug/settings'
    | '/c/$slug/wall'
    | '/c/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/profile'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug/album'
    | '/c/$slug/events'
    | '/c/$slug/home'
    | '/c/$slug/join'
    | '/c/$slug/photos'
    | '/c/$slug/settings'
    | '/c/$slug/wall'
    | '/c/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  CampfiresNewRoute: typeof CampfiresNewRoute
  CSlugAlbumRoute: typeof CSlugAlbumRoute
  CSlugEventsRoute: typeof CSlugEventsRoute
  CSlugHomeRoute: typeof CSlugHomeRoute
  CSlugJoinRoute: typeof CSlugJoinRoute
  CSlugPhotosRoute: typeof CSlugPhotosRoute
  CSlugSettingsRoute: typeof CSlugSettingsRoute
  CSlugWallRoute: typeof CSlugWallRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campfires/new': {
      id: '/campfires/new'
      path: '/campfires/new'
      fullPath: '/campfires/new'
      preLoaderRoute: typeof CampfiresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/c/$slug'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/wall': {
      id: '/c/$slug/wall'
      path: '/c/$slug/wall'
      fullPath: '/c/$slug/wall'
      preLoaderRoute: typeof CSlugWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/settings': {
      id: '/c/$slug/settings'
      path: '/c/$slug/settings'
      fullPath: '/c/$slug/settings'
      preLoaderRoute: typeof CSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/photos': {
      id: '/c/$slug/photos'
      path: '/c/$slug/photos'
      fullPath: '/c/$slug/photos'
      preLoaderRoute: typeof CSlugPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/join': {
      id: '/c/$slug/join'
      path: '/c/$slug/join'
      fullPath: '/c/$slug/join'
      preLoaderRoute: typeof CSlugJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/home': {
      id: '/c/$slug/home'
      path: '/c/$slug/home'
      fullPath: '/c/$slug/home'
      preLoaderRoute: typeof CSlugHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/events': {
      id: '/c/$slug/events'
      path: '/c/$slug/events'
      fullPath: '/c/$slug/events'
      preLoaderRoute: typeof CSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/album': {
      id: '/c/$slug/album'
      path: '/c/$slug/album'
      fullPath: '/c/$slug/album'
      preLoaderRoute: typeof CSlugAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  CampfiresNewRoute: CampfiresNewRoute,
  CSlugAlbumRoute: CSlugAlbumRoute,
  CSlugEventsRoute: CSlugEventsRoute,
  CSlugHomeRoute: CSlugHomeRoute,
  CSlugJoinRoute: CSlugJoinRoute,
  CSlugPhotosRoute: CSlugPhotosRoute,
  CSlugSettingsRoute: CSlugSettingsRoute,
  CSlugWallRoute: CSlugWallRoute,
  CSlugIndexRoute: CSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
