/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampfiresNewRouteImport } from './routes/campfires/new'
import { Route as CSlugIndexRouteImport } from './routes/c/$slug/index'
import { Route as CSlugWallRouteImport } from './routes/c/$slug/wall'
import { Route as CSlugJoinRouteImport } from './routes/c/$slug/join'
import { Route as CSlugAlbumRouteImport } from './routes/c/$slug/album'
import { Route as CSlugHostRouteRouteImport } from './routes/c/$slug/_host/route'
import { Route as CSlugHostSettingsRouteImport } from './routes/c/$slug/_host/settings'
import { Route as CSlugHostPhotosRouteImport } from './routes/c/$slug/_host/photos'
import { Route as CSlugHostHomeRouteImport } from './routes/c/$slug/_host/home'
import { Route as CSlugHostEventsRouteImport } from './routes/c/$slug/_host/events'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampfiresNewRoute = CampfiresNewRouteImport.update({
  id: '/campfires/new',
  path: '/campfires/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/c/$slug/',
  path: '/c/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugWallRoute = CSlugWallRouteImport.update({
  id: '/c/$slug/wall',
  path: '/c/$slug/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugJoinRoute = CSlugJoinRouteImport.update({
  id: '/c/$slug/join',
  path: '/c/$slug/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugAlbumRoute = CSlugAlbumRouteImport.update({
  id: '/c/$slug/album',
  path: '/c/$slug/album',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugHostRouteRoute = CSlugHostRouteRouteImport.update({
  id: '/c/$slug/_host',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugHostSettingsRoute = CSlugHostSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CSlugHostRouteRoute,
} as any)
const CSlugHostPhotosRoute = CSlugHostPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => CSlugHostRouteRoute,
} as any)
const CSlugHostHomeRoute = CSlugHostHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CSlugHostRouteRoute,
} as any)
const CSlugHostEventsRoute = CSlugHostEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CSlugHostRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brand': typeof BrandRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug': typeof CSlugHostRouteRouteWithChildren
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/events': typeof CSlugHostEventsRoute
  '/c/$slug/home': typeof CSlugHostHomeRoute
  '/c/$slug/photos': typeof CSlugHostPhotosRoute
  '/c/$slug/settings': typeof CSlugHostSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brand': typeof BrandRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug/events': typeof CSlugHostEventsRoute
  '/c/$slug/home': typeof CSlugHostHomeRoute
  '/c/$slug/photos': typeof CSlugHostPhotosRoute
  '/c/$slug/settings': typeof CSlugHostSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/brand': typeof BrandRoute
  '/sign-in': typeof SignInRoute
  '/campfires/new': typeof CampfiresNewRoute
  '/c/$slug/_host': typeof CSlugHostRouteRouteWithChildren
  '/c/$slug/album': typeof CSlugAlbumRoute
  '/c/$slug/join': typeof CSlugJoinRoute
  '/c/$slug/wall': typeof CSlugWallRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/_host/events': typeof CSlugHostEventsRoute
  '/c/$slug/_host/home': typeof CSlugHostHomeRoute
  '/c/$slug/_host/photos': typeof CSlugHostPhotosRoute
  '/c/$slug/_host/settings': typeof CSlugHostSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/brand'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug'
    | '/c/$slug/album'
    | '/c/$slug/join'
    | '/c/$slug/wall'
    | '/c/$slug/'
    | '/c/$slug/events'
    | '/c/$slug/home'
    | '/c/$slug/photos'
    | '/c/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/brand'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug'
    | '/c/$slug/album'
    | '/c/$slug/join'
    | '/c/$slug/wall'
    | '/c/$slug/events'
    | '/c/$slug/home'
    | '/c/$slug/photos'
    | '/c/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/brand'
    | '/sign-in'
    | '/campfires/new'
    | '/c/$slug/_host'
    | '/c/$slug/album'
    | '/c/$slug/join'
    | '/c/$slug/wall'
    | '/c/$slug/'
    | '/c/$slug/_host/events'
    | '/c/$slug/_host/home'
    | '/c/$slug/_host/photos'
    | '/c/$slug/_host/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BrandRoute: typeof BrandRoute
  SignInRoute: typeof SignInRoute
  CampfiresNewRoute: typeof CampfiresNewRoute
  CSlugHostRouteRoute: typeof CSlugHostRouteRouteWithChildren
  CSlugAlbumRoute: typeof CSlugAlbumRoute
  CSlugJoinRoute: typeof CSlugJoinRoute
  CSlugWallRoute: typeof CSlugWallRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campfires/new': {
      id: '/campfires/new'
      path: '/campfires/new'
      fullPath: '/campfires/new'
      preLoaderRoute: typeof CampfiresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/c/$slug'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/wall': {
      id: '/c/$slug/wall'
      path: '/c/$slug/wall'
      fullPath: '/c/$slug/wall'
      preLoaderRoute: typeof CSlugWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/join': {
      id: '/c/$slug/join'
      path: '/c/$slug/join'
      fullPath: '/c/$slug/join'
      preLoaderRoute: typeof CSlugJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/album': {
      id: '/c/$slug/album'
      path: '/c/$slug/album'
      fullPath: '/c/$slug/album'
      preLoaderRoute: typeof CSlugAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/_host': {
      id: '/c/$slug/_host'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugHostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/_host/settings': {
      id: '/c/$slug/_host/settings'
      path: '/settings'
      fullPath: '/c/$slug/settings'
      preLoaderRoute: typeof CSlugHostSettingsRouteImport
      parentRoute: typeof CSlugHostRouteRoute
    }
    '/c/$slug/_host/photos': {
      id: '/c/$slug/_host/photos'
      path: '/photos'
      fullPath: '/c/$slug/photos'
      preLoaderRoute: typeof CSlugHostPhotosRouteImport
      parentRoute: typeof CSlugHostRouteRoute
    }
    '/c/$slug/_host/home': {
      id: '/c/$slug/_host/home'
      path: '/home'
      fullPath: '/c/$slug/home'
      preLoaderRoute: typeof CSlugHostHomeRouteImport
      parentRoute: typeof CSlugHostRouteRoute
    }
    '/c/$slug/_host/events': {
      id: '/c/$slug/_host/events'
      path: '/events'
      fullPath: '/c/$slug/events'
      preLoaderRoute: typeof CSlugHostEventsRouteImport
      parentRoute: typeof CSlugHostRouteRoute
    }
  }
}

interface CSlugHostRouteRouteChildren {
  CSlugHostEventsRoute: typeof CSlugHostEventsRoute
  CSlugHostHomeRoute: typeof CSlugHostHomeRoute
  CSlugHostPhotosRoute: typeof CSlugHostPhotosRoute
  CSlugHostSettingsRoute: typeof CSlugHostSettingsRoute
}

const CSlugHostRouteRouteChildren: CSlugHostRouteRouteChildren = {
  CSlugHostEventsRoute: CSlugHostEventsRoute,
  CSlugHostHomeRoute: CSlugHostHomeRoute,
  CSlugHostPhotosRoute: CSlugHostPhotosRoute,
  CSlugHostSettingsRoute: CSlugHostSettingsRoute,
}

const CSlugHostRouteRouteWithChildren = CSlugHostRouteRoute._addFileChildren(
  CSlugHostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BrandRoute: BrandRoute,
  SignInRoute: SignInRoute,
  CampfiresNewRoute: CampfiresNewRoute,
  CSlugHostRouteRoute: CSlugHostRouteRouteWithChildren,
  CSlugAlbumRoute: CSlugAlbumRoute,
  CSlugJoinRoute: CSlugJoinRoute,
  CSlugWallRoute: CSlugWallRoute,
  CSlugIndexRoute: CSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
